services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
