apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: flask-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: custom-postgres:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: flask-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
