services:
  nginx:
    image: nginx:latest
    container_name: nginx1
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
