version: '3.8'

services:
  zabbix-agent2:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent2
    environment:
      - ZBX_HOSTNAME=<chose a name>
      - ZBX_SERVER_HOST=<ip of zabbix proxy or agent>
      - ZBX_SERVER_PORT=10050
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
