version: '3.8'

services:
  zabbix-proxy-sqlite3:
    image: zabbix/zabbix-proxy-sqlite3:latest
    container_name: zabbix-proxy-sqlite3
    environment:
      - ZBX_SERVER_HOST=<ip of zabbix server>
      - ZBX_HOSTNAME=zabbix-proxy
      - ZBX_SERVER_PORT=10051
    volumes:
      - ./zabbix_proxy.db:/var/lib/zabbix/zabbix_proxy.db
    ports:
      - "10051:10051"
    networks:
      - zabbix-net
    restart: always
networks:
  zabbix-net:
    driver: bridge
