version: '3.8'
services:
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      - ZBX_HOSTNAME=<chose a name>
      - ZBX_SERVER_HOST=<ip of zabbix proxy or agent>
      - ZBX_SERVER_PORT=10051
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
