apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000        # Port open inside the pod
      targetPort: 5000  # Port the container listens on
      nodePort: 30080   # Port accessible from outside (between 30000 and 32767)
