apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: flask-project
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
