apiVersion: v1
kind: Pod
metadata:
  name: flask-postgres-pod
  labels:
    app: flask-postgres-pod
spec:
  containers:
    - name: flask-app
      image: flask-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 5000
      env:
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_DB
          value: mydatabase
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
    - name: postgres-db
      image: custom-postgres:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: mydatabase
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-storage
      emptyDir: {}
